/**
 * @packageDocumentation
 * @module api.functional.news
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * @controller NewsController.getNews
 * @path POST /news
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getNews(
  connection: IConnection,
  body: getNews.Body,
): Promise<getNews.Output> {
  return true === connection.simulate
    ? getNews.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...getNews.METADATA,
          template: getNews.METADATA.path,
          path: getNews.path(),
        },
        body,
      );
}
export namespace getNews {
  export type Body = { company: string };
  export type Output = Array<any>;

  export const METADATA = {
    method: "POST",
    path: "/news",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/news";
  export const random = (): Array<any> => typia.random<Array<any>>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
