/**
 * @packageDocumentation
 * @module api.functional.reports.mirae_asset.download
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * 미래에셋증권 보고서 PDF 다운로드
 * @controller ReportsController.downloadMiraeAssetReport
 * @path POST /reports/mirae-asset/download
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function downloadMiraeAssetReport(
  connection: IConnection,
  body: downloadMiraeAssetReport.Body,
): Promise<downloadMiraeAssetReport.Output> {
  return true === connection.simulate
    ? downloadMiraeAssetReport.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...downloadMiraeAssetReport.METADATA,
          template: downloadMiraeAssetReport.METADATA.path,
          path: downloadMiraeAssetReport.path(),
        },
        body,
      );
}
export namespace downloadMiraeAssetReport {
  export type Body = { downloadUrl: string; outputDir?: string };
  export type Output = { filePath: string };

  export const METADATA = {
    method: "POST",
    path: "/reports/mirae-asset/download",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/reports/mirae-asset/download";
  export const random = (): { filePath: string } =>
    typia.random<{ filePath: string }>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
