/**
 * @packageDocumentation
 * @module api.functional.reports.convert_multiple_pdfs_to_markdown
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * 여러 PDF 파일을 일괄 마크다운으로 변환
 * @controller ReportsController.convertMultiplePdfsToMarkdown
 * @path POST /reports/convert-multiple-pdfs-to-markdown
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function convertMultiplePdfsToMarkdown(
  connection: IConnection,
  body: convertMultiplePdfsToMarkdown.Body,
): Promise<convertMultiplePdfsToMarkdown.Output> {
  return true === connection.simulate
    ? convertMultiplePdfsToMarkdown.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...convertMultiplePdfsToMarkdown.METADATA,
          template: convertMultiplePdfsToMarkdown.METADATA.path,
          path: convertMultiplePdfsToMarkdown.path(),
        },
        body,
      );
}
export namespace convertMultiplePdfsToMarkdown {
  export type Body = { pdfFilePaths: string[]; outputDir?: string };
  export type Output = {
    markdown: string;
    fileName: string;
    success: boolean;
    error?: string;
  }[];

  export const METADATA = {
    method: "POST",
    path: "/reports/convert-multiple-pdfs-to-markdown",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/reports/convert-multiple-pdfs-to-markdown";
  export const random = (): {
    markdown: string;
    fileName: string;
    success: boolean;
    error?: string;
  }[] =>
    typia.random<
      { markdown: string; fileName: string; success: boolean; error?: string }[]
    >();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
