/**
 * @packageDocumentation
 * @module api.functional.reports.mirae_asset.download_and_convert
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * 보고서 다운로드 후 자동으로 마크다운 변환
 * @controller ReportsController.downloadAndConvertReport
 * @path POST /reports/mirae-asset/download-and-convert
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function downloadAndConvertReport(
  connection: IConnection,
  body: downloadAndConvertReport.Body,
): Promise<downloadAndConvertReport.Output> {
  return true === connection.simulate
    ? downloadAndConvertReport.simulate(connection, body)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...downloadAndConvertReport.METADATA,
          template: downloadAndConvertReport.METADATA.path,
          path: downloadAndConvertReport.path(),
        },
        body,
      );
}
export namespace downloadAndConvertReport {
  export type Body = { downloadUrl: string; outputDir?: string };
  export type Output = {
    pdfFilePath: string;
    markdown: string;
    markdownFileName: string;
    success: boolean;
    error?: string;
  };

  export const METADATA = {
    method: "POST",
    path: "/reports/mirae-asset/download-and-convert",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/reports/mirae-asset/download-and-convert";
  export const random = (): {
    pdfFilePath: string;
    markdown: string;
    markdownFileName: string;
    success: boolean;
    error?: string;
  } =>
    typia.random<{
      pdfFilePath: string;
      markdown: string;
      markdownFileName: string;
      success: boolean;
      error?: string;
    }>();
  export const simulate = (connection: IConnection, body: Body): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(body));
    return random();
  };
}
